In [1]:
from joblib import dump,load
import numpy as np 
model = load('ML_model.joblib')

In [2]:
features = np.array([[-0.43942006,  5.12628155, -1.12165014, -0.27288841, -1.42262747,
       -11.44024664, -1.31238772,  2.61111401, -14.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -10.86091034]])
model.predict(features)

array([24.297])

In [3]:
features = np.array([[-9.43942006,  5.12628155, -1.12165014, -0.27288841, -1.42262747,
       -11.44024664, -1.31238772,  2.61111401, -14.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -10.86091034]])
model.predict(features)

array([24.337])

In [4]:
features = np.array([[-9.43942006,  5.12628155, -1.12165014, -0.27288841, -1.42262747,
       -9.44024664, -1.31238772,  2.61111401, -4.0016859 , -0.5778192 ,
       -.1197491834,  0.41164221, -10.86091034]])
model.predict(features)

array([24.284])